// Copyright 2026 The Cypherium Authors
// This file is part of the Cypherium library.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignatureAlgorithm int32

const (
	SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED SignatureAlgorithm = 0
	SignatureAlgorithm_SIGNATURE_ALGORITHM_ED25519     SignatureAlgorithm = 1
	SignatureAlgorithm_SIGNATURE_ALGORITHM_P256_SHA256 SignatureAlgorithm = 2
	SignatureAlgorithm_SIGNATURE_ALGORITHM_EIP712      SignatureAlgorithm = 3
)

// Enum value maps for SignatureAlgorithm.
var (
	SignatureAlgorithm_name = map[int32]string{
		0: "SIGNATURE_ALGORITHM_UNSPECIFIED",
		1: "SIGNATURE_ALGORITHM_ED25519",
		2: "SIGNATURE_ALGORITHM_P256_SHA256",
		3: "SIGNATURE_ALGORITHM_EIP712",
	}
	SignatureAlgorithm_value = map[string]int32{
		"SIGNATURE_ALGORITHM_UNSPECIFIED": 0,
		"SIGNATURE_ALGORITHM_ED25519":     1,
		"SIGNATURE_ALGORITHM_P256_SHA256": 2,
		"SIGNATURE_ALGORITHM_EIP712":      3,
	}
)

func (x SignatureAlgorithm) Enum() *SignatureAlgorithm {
	p := new(SignatureAlgorithm)
	*p = x
	return p
}

func (x SignatureAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (SignatureAlgorithm) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x SignatureAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureAlgorithm.Descriptor instead.
func (SignatureAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

type PrincipalKind int32

const (
	PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED PrincipalKind = 0
	PrincipalKind_PRINCIPAL_KIND_PROVIDER    PrincipalKind = 1
	PrincipalKind_PRINCIPAL_KIND_AGENT       PrincipalKind = 2
	PrincipalKind_PRINCIPAL_KIND_HOST        PrincipalKind = 3
	PrincipalKind_PRINCIPAL_KIND_DEVICE      PrincipalKind = 4
	PrincipalKind_PRINCIPAL_KIND_MINER       PrincipalKind = 5
	PrincipalKind_PRINCIPAL_KIND_RUNNER      PrincipalKind = 6
	PrincipalKind_PRINCIPAL_KIND_BUYER       PrincipalKind = 7
	PrincipalKind_PRINCIPAL_KIND_SERVICE     PrincipalKind = 8
	PrincipalKind_PRINCIPAL_KIND_HUMAN_USER  PrincipalKind = 9
)

// Enum value maps for PrincipalKind.
var (
	PrincipalKind_name = map[int32]string{
		0: "PRINCIPAL_KIND_UNSPECIFIED",
		1: "PRINCIPAL_KIND_PROVIDER",
		2: "PRINCIPAL_KIND_AGENT",
		3: "PRINCIPAL_KIND_HOST",
		4: "PRINCIPAL_KIND_DEVICE",
		5: "PRINCIPAL_KIND_MINER",
		6: "PRINCIPAL_KIND_RUNNER",
		7: "PRINCIPAL_KIND_BUYER",
		8: "PRINCIPAL_KIND_SERVICE",
		9: "PRINCIPAL_KIND_HUMAN_USER",
	}
	PrincipalKind_value = map[string]int32{
		"PRINCIPAL_KIND_UNSPECIFIED": 0,
		"PRINCIPAL_KIND_PROVIDER":    1,
		"PRINCIPAL_KIND_AGENT":       2,
		"PRINCIPAL_KIND_HOST":        3,
		"PRINCIPAL_KIND_DEVICE":      4,
		"PRINCIPAL_KIND_MINER":       5,
		"PRINCIPAL_KIND_RUNNER":      6,
		"PRINCIPAL_KIND_BUYER":       7,
		"PRINCIPAL_KIND_SERVICE":     8,
		"PRINCIPAL_KIND_HUMAN_USER":  9,
	}
)

func (x PrincipalKind) Enum() *PrincipalKind {
	p := new(PrincipalKind)
	*p = x
	return p
}

func (x PrincipalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (PrincipalKind) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[1]
}

func (x PrincipalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalKind.Descriptor instead.
func (PrincipalKind) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

type SchemaVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersion) Reset() {
	*x = SchemaVersion{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersion) ProtoMessage() {}

func (x *SchemaVersion) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersion.ProtoReflect.Descriptor instead.
func (*SchemaVersion) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SchemaVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// RecordMetadata is embedded by immutable foundation records. All time values
// are signed UTC Unix nanoseconds. policy_digests_sha256 is a mathematical set
// in the CCSE registry even though Protobuf transports it as repeated bytes.
type RecordMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion         *SchemaVersion         `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RecordId              string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	CreatedAtUnixNano     int64                  `protobuf:"varint,3,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	IntegrityDigestSha256 []byte                 `protobuf:"bytes,4,opt,name=integrity_digest_sha256,json=integrityDigestSha256,proto3" json:"integrity_digest_sha256,omitempty"`
	HomeRegion            string                 `protobuf:"bytes,5,opt,name=home_region,json=homeRegion,proto3" json:"home_region,omitempty"`
	WriterEpoch           uint64                 `protobuf:"varint,6,opt,name=writer_epoch,json=writerEpoch,proto3" json:"writer_epoch,omitempty"`
	StateVersion          uint64                 `protobuf:"varint,7,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	IdempotencyKey        []byte                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PolicyDigestsSha256   [][]byte               `protobuf:"bytes,9,rep,name=policy_digests_sha256,json=policyDigestsSha256,proto3" json:"policy_digests_sha256,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RecordMetadata) Reset() {
	*x = RecordMetadata{}
	mi := &file_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMetadata) ProtoMessage() {}

func (x *RecordMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMetadata.ProtoReflect.Descriptor instead.
func (*RecordMetadata) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *RecordMetadata) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *RecordMetadata) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordMetadata) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

func (x *RecordMetadata) GetIntegrityDigestSha256() []byte {
	if x != nil {
		return x.IntegrityDigestSha256
	}
	return nil
}

func (x *RecordMetadata) GetHomeRegion() string {
	if x != nil {
		return x.HomeRegion
	}
	return ""
}

func (x *RecordMetadata) GetWriterEpoch() uint64 {
	if x != nil {
		return x.WriterEpoch
	}
	return 0
}

func (x *RecordMetadata) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *RecordMetadata) GetIdempotencyKey() []byte {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

func (x *RecordMetadata) GetPolicyDigestsSha256() [][]byte {
	if x != nil {
		return x.PolicyDigestsSha256
	}
	return nil
}

// TransportSigningDomain carries the inputs from which the separate CCSE
// Domain projection is constructed. audience is a set. Optional scalar
// presence is significant and is preserved with proto3 optional fields.
type TransportSigningDomain struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Purpose              string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	SenderIdentity       string                 `protobuf:"bytes,2,opt,name=sender_identity,json=senderIdentity,proto3" json:"sender_identity,omitempty"`
	Audience             []string               `protobuf:"bytes,3,rep,name=audience,proto3" json:"audience,omitempty"`
	TenantOrganization   *string                `protobuf:"bytes,4,opt,name=tenant_organization,json=tenantOrganization,proto3,oneof" json:"tenant_organization,omitempty"`
	ProviderOrganization *string                `protobuf:"bytes,5,opt,name=provider_organization,json=providerOrganization,proto3,oneof" json:"provider_organization,omitempty"`
	ChainIdUint256Be     []byte                 `protobuf:"bytes,6,opt,name=chain_id_uint256_be,json=chainIdUint256Be,proto3" json:"chain_id_uint256_be,omitempty"`
	GenesisHashSha256    []byte                 `protobuf:"bytes,7,opt,name=genesis_hash_sha256,json=genesisHashSha256,proto3" json:"genesis_hash_sha256,omitempty"`
	Environment          string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	ProtocolVersion      *ProtocolVersion       `protobuf:"bytes,9,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion        *SchemaVersion         `protobuf:"bytes,10,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SignatureAlgorithm   SignatureAlgorithm     `protobuf:"varint,11,opt,name=signature_algorithm,json=signatureAlgorithm,proto3,enum=cph.aiinfra.common.v1.SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	SignatureKeyId       string                 `protobuf:"bytes,12,opt,name=signature_key_id,json=signatureKeyId,proto3" json:"signature_key_id,omitempty"`
	IssuedAtUnixNano     int64                  `protobuf:"varint,13,opt,name=issued_at_unix_nano,json=issuedAtUnixNano,proto3" json:"issued_at_unix_nano,omitempty"`
	ExpiresAtUnixNano    int64                  `protobuf:"varint,14,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	// Types that are valid to be assigned to ReplayGuard:
	//
	//	*TransportSigningDomain_Sequence
	//	*TransportSigningDomain_ExpectedGeneration
	ReplayGuard    isTransportSigningDomain_ReplayGuard `protobuf_oneof:"replay_guard"`
	ReplayDomainId string                               `protobuf:"bytes,17,opt,name=replay_domain_id,json=replayDomainId,proto3" json:"replay_domain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransportSigningDomain) Reset() {
	*x = TransportSigningDomain{}
	mi := &file_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportSigningDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportSigningDomain) ProtoMessage() {}

func (x *TransportSigningDomain) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportSigningDomain.ProtoReflect.Descriptor instead.
func (*TransportSigningDomain) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *TransportSigningDomain) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *TransportSigningDomain) GetSenderIdentity() string {
	if x != nil {
		return x.SenderIdentity
	}
	return ""
}

func (x *TransportSigningDomain) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *TransportSigningDomain) GetTenantOrganization() string {
	if x != nil && x.TenantOrganization != nil {
		return *x.TenantOrganization
	}
	return ""
}

func (x *TransportSigningDomain) GetProviderOrganization() string {
	if x != nil && x.ProviderOrganization != nil {
		return *x.ProviderOrganization
	}
	return ""
}

func (x *TransportSigningDomain) GetChainIdUint256Be() []byte {
	if x != nil {
		return x.ChainIdUint256Be
	}
	return nil
}

func (x *TransportSigningDomain) GetGenesisHashSha256() []byte {
	if x != nil {
		return x.GenesisHashSha256
	}
	return nil
}

func (x *TransportSigningDomain) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *TransportSigningDomain) GetProtocolVersion() *ProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *TransportSigningDomain) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *TransportSigningDomain) GetSignatureAlgorithm() SignatureAlgorithm {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED
}

func (x *TransportSigningDomain) GetSignatureKeyId() string {
	if x != nil {
		return x.SignatureKeyId
	}
	return ""
}

func (x *TransportSigningDomain) GetIssuedAtUnixNano() int64 {
	if x != nil {
		return x.IssuedAtUnixNano
	}
	return 0
}

func (x *TransportSigningDomain) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

func (x *TransportSigningDomain) GetReplayGuard() isTransportSigningDomain_ReplayGuard {
	if x != nil {
		return x.ReplayGuard
	}
	return nil
}

func (x *TransportSigningDomain) GetSequence() uint64 {
	if x != nil {
		if x, ok := x.ReplayGuard.(*TransportSigningDomain_Sequence); ok {
			return x.Sequence
		}
	}
	return 0
}

func (x *TransportSigningDomain) GetExpectedGeneration() uint64 {
	if x != nil {
		if x, ok := x.ReplayGuard.(*TransportSigningDomain_ExpectedGeneration); ok {
			return x.ExpectedGeneration
		}
	}
	return 0
}

func (x *TransportSigningDomain) GetReplayDomainId() string {
	if x != nil {
		return x.ReplayDomainId
	}
	return ""
}

type isTransportSigningDomain_ReplayGuard interface {
	isTransportSigningDomain_ReplayGuard()
}

type TransportSigningDomain_Sequence struct {
	Sequence uint64 `protobuf:"varint,15,opt,name=sequence,proto3,oneof"`
}

type TransportSigningDomain_ExpectedGeneration struct {
	ExpectedGeneration uint64 `protobuf:"varint,16,opt,name=expected_generation,json=expectedGeneration,proto3,oneof"`
}

func (*TransportSigningDomain_Sequence) isTransportSigningDomain_ReplayGuard() {}

func (*TransportSigningDomain_ExpectedGeneration) isTransportSigningDomain_ReplayGuard() {}

type TransportExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   uint32                 `protobuf:"varint,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Critical      bool                   `protobuf:"varint,2,opt,name=critical,proto3" json:"critical,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportExtension) Reset() {
	*x = TransportExtension{}
	mi := &file_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportExtension) ProtoMessage() {}

func (x *TransportExtension) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportExtension.ProtoReflect.Descriptor instead.
func (*TransportExtension) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *TransportExtension) GetExtensionId() uint32 {
	if x != nil {
		return x.ExtensionId
	}
	return 0
}

func (x *TransportExtension) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *TransportExtension) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// TransportEnvelope is not itself a signing serialization. Receivers rebuild
// and validate the CCSE envelope, domain, and payload projections and then
// verify signature over SHA-256(CCSE preimage).
type TransportEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion   *ProtocolVersion       `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion     *SchemaVersion         `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	MessageId         []byte                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CorrelationId     []byte                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId       []byte                 `protobuf:"bytes,5,opt,name=causation_id,json=causationId,proto3,oneof" json:"causation_id,omitempty"`
	SenderIdentity    string                 `protobuf:"bytes,6,opt,name=sender_identity,json=senderIdentity,proto3" json:"sender_identity,omitempty"`
	ChainIdUint256Be  []byte                 `protobuf:"bytes,7,opt,name=chain_id_uint256_be,json=chainIdUint256Be,proto3" json:"chain_id_uint256_be,omitempty"`
	Environment       string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	IssuedAtUnixNano  int64                  `protobuf:"varint,9,opt,name=issued_at_unix_nano,json=issuedAtUnixNano,proto3" json:"issued_at_unix_nano,omitempty"`
	ExpiresAtUnixNano int64                  `protobuf:"varint,10,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	// Types that are valid to be assigned to ReplayGuard:
	//
	//	*TransportEnvelope_Sequence
	//	*TransportEnvelope_ExpectedGeneration
	ReplayGuard         isTransportEnvelope_ReplayGuard `protobuf_oneof:"replay_guard"`
	PayloadDigestSha256 []byte                          `protobuf:"bytes,13,opt,name=payload_digest_sha256,json=payloadDigestSha256,proto3" json:"payload_digest_sha256,omitempty"`
	SignatureAlgorithm  SignatureAlgorithm              `protobuf:"varint,14,opt,name=signature_algorithm,json=signatureAlgorithm,proto3,enum=cph.aiinfra.common.v1.SignatureAlgorithm" json:"signature_algorithm,omitempty"`
	SignatureKeyId      string                          `protobuf:"bytes,15,opt,name=signature_key_id,json=signatureKeyId,proto3" json:"signature_key_id,omitempty"`
	Extensions          []*TransportExtension           `protobuf:"bytes,16,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Signature           []byte                          `protobuf:"bytes,17,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransportEnvelope) Reset() {
	*x = TransportEnvelope{}
	mi := &file_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportEnvelope) ProtoMessage() {}

func (x *TransportEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportEnvelope.ProtoReflect.Descriptor instead.
func (*TransportEnvelope) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *TransportEnvelope) GetProtocolVersion() *ProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *TransportEnvelope) GetSchemaVersion() *SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return nil
}

func (x *TransportEnvelope) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *TransportEnvelope) GetCorrelationId() []byte {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *TransportEnvelope) GetCausationId() []byte {
	if x != nil {
		return x.CausationId
	}
	return nil
}

func (x *TransportEnvelope) GetSenderIdentity() string {
	if x != nil {
		return x.SenderIdentity
	}
	return ""
}

func (x *TransportEnvelope) GetChainIdUint256Be() []byte {
	if x != nil {
		return x.ChainIdUint256Be
	}
	return nil
}

func (x *TransportEnvelope) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *TransportEnvelope) GetIssuedAtUnixNano() int64 {
	if x != nil {
		return x.IssuedAtUnixNano
	}
	return 0
}

func (x *TransportEnvelope) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

func (x *TransportEnvelope) GetReplayGuard() isTransportEnvelope_ReplayGuard {
	if x != nil {
		return x.ReplayGuard
	}
	return nil
}

func (x *TransportEnvelope) GetSequence() uint64 {
	if x != nil {
		if x, ok := x.ReplayGuard.(*TransportEnvelope_Sequence); ok {
			return x.Sequence
		}
	}
	return 0
}

func (x *TransportEnvelope) GetExpectedGeneration() uint64 {
	if x != nil {
		if x, ok := x.ReplayGuard.(*TransportEnvelope_ExpectedGeneration); ok {
			return x.ExpectedGeneration
		}
	}
	return 0
}

func (x *TransportEnvelope) GetPayloadDigestSha256() []byte {
	if x != nil {
		return x.PayloadDigestSha256
	}
	return nil
}

func (x *TransportEnvelope) GetSignatureAlgorithm() SignatureAlgorithm {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return SignatureAlgorithm_SIGNATURE_ALGORITHM_UNSPECIFIED
}

func (x *TransportEnvelope) GetSignatureKeyId() string {
	if x != nil {
		return x.SignatureKeyId
	}
	return ""
}

func (x *TransportEnvelope) GetExtensions() []*TransportExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *TransportEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isTransportEnvelope_ReplayGuard interface {
	isTransportEnvelope_ReplayGuard()
}

type TransportEnvelope_Sequence struct {
	Sequence uint64 `protobuf:"varint,11,opt,name=sequence,proto3,oneof"`
}

type TransportEnvelope_ExpectedGeneration struct {
	ExpectedGeneration uint64 `protobuf:"varint,12,opt,name=expected_generation,json=expectedGeneration,proto3,oneof"`
}

func (*TransportEnvelope_Sequence) isTransportEnvelope_ReplayGuard() {}

func (*TransportEnvelope_ExpectedGeneration) isTransportEnvelope_ReplayGuard() {}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\x15cph.aiinfra.common.v1\";\n" +
	"\rSchemaVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"\xa9\x03\n" +
	"\x0eRecordMetadata\x12K\n" +
	"\x0eschema_version\x18\x01 \x01(\v2$.cph.aiinfra.common.v1.SchemaVersionR\rschemaVersion\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12/\n" +
	"\x14created_at_unix_nano\x18\x03 \x01(\x03R\x11createdAtUnixNano\x126\n" +
	"\x17integrity_digest_sha256\x18\x04 \x01(\fR\x15integrityDigestSha256\x12\x1f\n" +
	"\vhome_region\x18\x05 \x01(\tR\n" +
	"homeRegion\x12!\n" +
	"\fwriter_epoch\x18\x06 \x01(\x04R\vwriterEpoch\x12#\n" +
	"\rstate_version\x18\a \x01(\x04R\fstateVersion\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\fR\x0eidempotencyKey\x122\n" +
	"\x15policy_digests_sha256\x18\t \x03(\fR\x13policyDigestsSha256\"\xab\a\n" +
	"\x16TransportSigningDomain\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12'\n" +
	"\x0fsender_identity\x18\x02 \x01(\tR\x0esenderIdentity\x12\x1a\n" +
	"\baudience\x18\x03 \x03(\tR\baudience\x124\n" +
	"\x13tenant_organization\x18\x04 \x01(\tH\x01R\x12tenantOrganization\x88\x01\x01\x128\n" +
	"\x15provider_organization\x18\x05 \x01(\tH\x02R\x14providerOrganization\x88\x01\x01\x12-\n" +
	"\x13chain_id_uint256_be\x18\x06 \x01(\fR\x10chainIdUint256Be\x12.\n" +
	"\x13genesis_hash_sha256\x18\a \x01(\fR\x11genesisHashSha256\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12Q\n" +
	"\x10protocol_version\x18\t \x01(\v2&.cph.aiinfra.common.v1.ProtocolVersionR\x0fprotocolVersion\x12K\n" +
	"\x0eschema_version\x18\n" +
	" \x01(\v2$.cph.aiinfra.common.v1.SchemaVersionR\rschemaVersion\x12Z\n" +
	"\x13signature_algorithm\x18\v \x01(\x0e2).cph.aiinfra.common.v1.SignatureAlgorithmR\x12signatureAlgorithm\x12(\n" +
	"\x10signature_key_id\x18\f \x01(\tR\x0esignatureKeyId\x12-\n" +
	"\x13issued_at_unix_nano\x18\r \x01(\x03R\x10issuedAtUnixNano\x12/\n" +
	"\x14expires_at_unix_nano\x18\x0e \x01(\x03R\x11expiresAtUnixNano\x12\x1c\n" +
	"\bsequence\x18\x0f \x01(\x04H\x00R\bsequence\x121\n" +
	"\x13expected_generation\x18\x10 \x01(\x04H\x00R\x12expectedGeneration\x12(\n" +
	"\x10replay_domain_id\x18\x11 \x01(\tR\x0ereplayDomainIdB\x0e\n" +
	"\freplay_guardB\x16\n" +
	"\x14_tenant_organizationB\x18\n" +
	"\x16_provider_organization\"i\n" +
	"\x12TransportExtension\x12!\n" +
	"\fextension_id\x18\x01 \x01(\rR\vextensionId\x12\x1a\n" +
	"\bcritical\x18\x02 \x01(\bR\bcritical\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x90\a\n" +
	"\x11TransportEnvelope\x12Q\n" +
	"\x10protocol_version\x18\x01 \x01(\v2&.cph.aiinfra.common.v1.ProtocolVersionR\x0fprotocolVersion\x12K\n" +
	"\x0eschema_version\x18\x02 \x01(\v2$.cph.aiinfra.common.v1.SchemaVersionR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\fR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\fR\rcorrelationId\x12&\n" +
	"\fcausation_id\x18\x05 \x01(\fH\x01R\vcausationId\x88\x01\x01\x12'\n" +
	"\x0fsender_identity\x18\x06 \x01(\tR\x0esenderIdentity\x12-\n" +
	"\x13chain_id_uint256_be\x18\a \x01(\fR\x10chainIdUint256Be\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12-\n" +
	"\x13issued_at_unix_nano\x18\t \x01(\x03R\x10issuedAtUnixNano\x12/\n" +
	"\x14expires_at_unix_nano\x18\n" +
	" \x01(\x03R\x11expiresAtUnixNano\x12\x1c\n" +
	"\bsequence\x18\v \x01(\x04H\x00R\bsequence\x121\n" +
	"\x13expected_generation\x18\f \x01(\x04H\x00R\x12expectedGeneration\x122\n" +
	"\x15payload_digest_sha256\x18\r \x01(\fR\x13payloadDigestSha256\x12Z\n" +
	"\x13signature_algorithm\x18\x0e \x01(\x0e2).cph.aiinfra.common.v1.SignatureAlgorithmR\x12signatureAlgorithm\x12(\n" +
	"\x10signature_key_id\x18\x0f \x01(\tR\x0esignatureKeyId\x12I\n" +
	"\n" +
	"extensions\x18\x10 \x03(\v2).cph.aiinfra.common.v1.TransportExtensionR\n" +
	"extensions\x12\x1c\n" +
	"\tsignature\x18\x11 \x01(\fR\tsignatureB\x0e\n" +
	"\freplay_guardB\x0f\n" +
	"\r_causation_id*\x9f\x01\n" +
	"\x12SignatureAlgorithm\x12#\n" +
	"\x1fSIGNATURE_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSIGNATURE_ALGORITHM_ED25519\x10\x01\x12#\n" +
	"\x1fSIGNATURE_ALGORITHM_P256_SHA256\x10\x02\x12\x1e\n" +
	"\x1aSIGNATURE_ALGORITHM_EIP712\x10\x03*\xa4\x02\n" +
	"\rPrincipalKind\x12\x1e\n" +
	"\x1aPRINCIPAL_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PRINCIPAL_KIND_PROVIDER\x10\x01\x12\x18\n" +
	"\x14PRINCIPAL_KIND_AGENT\x10\x02\x12\x17\n" +
	"\x13PRINCIPAL_KIND_HOST\x10\x03\x12\x19\n" +
	"\x15PRINCIPAL_KIND_DEVICE\x10\x04\x12\x18\n" +
	"\x14PRINCIPAL_KIND_MINER\x10\x05\x12\x19\n" +
	"\x15PRINCIPAL_KIND_RUNNER\x10\x06\x12\x18\n" +
	"\x14PRINCIPAL_KIND_BUYER\x10\a\x12\x1a\n" +
	"\x16PRINCIPAL_KIND_SERVICE\x10\b\x12\x1d\n" +
	"\x19PRINCIPAL_KIND_HUMAN_USER\x10\tB?Z=github.com/cypherium/cypher/aiinfra/schema/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_v1_common_proto_goTypes = []any{
	(SignatureAlgorithm)(0),        // 0: cph.aiinfra.common.v1.SignatureAlgorithm
	(PrincipalKind)(0),             // 1: cph.aiinfra.common.v1.PrincipalKind
	(*SchemaVersion)(nil),          // 2: cph.aiinfra.common.v1.SchemaVersion
	(*ProtocolVersion)(nil),        // 3: cph.aiinfra.common.v1.ProtocolVersion
	(*RecordMetadata)(nil),         // 4: cph.aiinfra.common.v1.RecordMetadata
	(*TransportSigningDomain)(nil), // 5: cph.aiinfra.common.v1.TransportSigningDomain
	(*TransportExtension)(nil),     // 6: cph.aiinfra.common.v1.TransportExtension
	(*TransportEnvelope)(nil),      // 7: cph.aiinfra.common.v1.TransportEnvelope
}
var file_common_v1_common_proto_depIdxs = []int32{
	2, // 0: cph.aiinfra.common.v1.RecordMetadata.schema_version:type_name -> cph.aiinfra.common.v1.SchemaVersion
	3, // 1: cph.aiinfra.common.v1.TransportSigningDomain.protocol_version:type_name -> cph.aiinfra.common.v1.ProtocolVersion
	2, // 2: cph.aiinfra.common.v1.TransportSigningDomain.schema_version:type_name -> cph.aiinfra.common.v1.SchemaVersion
	0, // 3: cph.aiinfra.common.v1.TransportSigningDomain.signature_algorithm:type_name -> cph.aiinfra.common.v1.SignatureAlgorithm
	3, // 4: cph.aiinfra.common.v1.TransportEnvelope.protocol_version:type_name -> cph.aiinfra.common.v1.ProtocolVersion
	2, // 5: cph.aiinfra.common.v1.TransportEnvelope.schema_version:type_name -> cph.aiinfra.common.v1.SchemaVersion
	0, // 6: cph.aiinfra.common.v1.TransportEnvelope.signature_algorithm:type_name -> cph.aiinfra.common.v1.SignatureAlgorithm
	6, // 7: cph.aiinfra.common.v1.TransportEnvelope.extensions:type_name -> cph.aiinfra.common.v1.TransportExtension
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	file_common_v1_common_proto_msgTypes[3].OneofWrappers = []any{
		(*TransportSigningDomain_Sequence)(nil),
		(*TransportSigningDomain_ExpectedGeneration)(nil),
	}
	file_common_v1_common_proto_msgTypes[5].OneofWrappers = []any{
		(*TransportEnvelope_Sequence)(nil),
		(*TransportEnvelope_ExpectedGeneration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
