// Copyright 2026 The Cypherium Authors
// This file is part of the Cypherium library.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transport/v1/foundation_transport.proto

package transportv1

import (
	v1 "github.com/cypherium/cypher/aiinfra/schema/common/v1"
	v11 "github.com/cypherium/cypher/aiinfra/schema/foundation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignedFoundationRecord is the transport wrapper for the fourteen foundation
// authorization payloads. The selected oneof arm is the sole source of the
// message type identifier; the wire format deliberately carries no second,
// caller-controlled numeric type ID.
//
// Protobuf bytes are never signed. Receivers strictly scan this wrapper,
// translate the selected payload to its CCSE-v1 projection, and verify the
// signature over the independently reconstructed CCSE record.
type SignedFoundationRecord struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SigningDomain *v1.TransportSigningDomain `protobuf:"bytes,1,opt,name=signing_domain,json=signingDomain,proto3" json:"signing_domain,omitempty"`
	Envelope      *v1.TransportEnvelope      `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SignedFoundationRecord_ProviderIdentity
	//	*SignedFoundationRecord_AgentIdentity
	//	*SignedFoundationRecord_HostIdentity
	//	*SignedFoundationRecord_DeviceIdentity
	//	*SignedFoundationRecord_MinerIdentity
	//	*SignedFoundationRecord_RunnerIdentity
	//	*SignedFoundationRecord_BuyerIdentity
	//	*SignedFoundationRecord_ServiceIdentity
	//	*SignedFoundationRecord_KeyLifecycle
	//	*SignedFoundationRecord_PolicyBundle
	//	*SignedFoundationRecord_AuditEvent
	//	*SignedFoundationRecord_EvidenceRecord
	//	*SignedFoundationRecord_ExperimentPlan
	//	*SignedFoundationRecord_OwnershipTransferAuthorization
	Payload       isSignedFoundationRecord_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedFoundationRecord) Reset() {
	*x = SignedFoundationRecord{}
	mi := &file_transport_v1_foundation_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedFoundationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedFoundationRecord) ProtoMessage() {}

func (x *SignedFoundationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_foundation_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedFoundationRecord.ProtoReflect.Descriptor instead.
func (*SignedFoundationRecord) Descriptor() ([]byte, []int) {
	return file_transport_v1_foundation_transport_proto_rawDescGZIP(), []int{0}
}

func (x *SignedFoundationRecord) GetSigningDomain() *v1.TransportSigningDomain {
	if x != nil {
		return x.SigningDomain
	}
	return nil
}

func (x *SignedFoundationRecord) GetEnvelope() *v1.TransportEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SignedFoundationRecord) GetPayload() isSignedFoundationRecord_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedFoundationRecord) GetProviderIdentity() *v11.ProviderIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_ProviderIdentity); ok {
			return x.ProviderIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetAgentIdentity() *v11.AgentIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_AgentIdentity); ok {
			return x.AgentIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetHostIdentity() *v11.HostIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_HostIdentity); ok {
			return x.HostIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetDeviceIdentity() *v11.DeviceIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_DeviceIdentity); ok {
			return x.DeviceIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetMinerIdentity() *v11.MinerIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_MinerIdentity); ok {
			return x.MinerIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetRunnerIdentity() *v11.RunnerIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_RunnerIdentity); ok {
			return x.RunnerIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetBuyerIdentity() *v11.BuyerIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_BuyerIdentity); ok {
			return x.BuyerIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetServiceIdentity() *v11.ServiceIdentity {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_ServiceIdentity); ok {
			return x.ServiceIdentity
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetKeyLifecycle() *v11.KeyLifecycle {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_KeyLifecycle); ok {
			return x.KeyLifecycle
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetPolicyBundle() *v11.PolicyBundle {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_PolicyBundle); ok {
			return x.PolicyBundle
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetAuditEvent() *v11.AuditEvent {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_AuditEvent); ok {
			return x.AuditEvent
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetEvidenceRecord() *v11.EvidenceRecord {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_EvidenceRecord); ok {
			return x.EvidenceRecord
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetExperimentPlan() *v11.ExperimentPlan {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_ExperimentPlan); ok {
			return x.ExperimentPlan
		}
	}
	return nil
}

func (x *SignedFoundationRecord) GetOwnershipTransferAuthorization() *v11.OwnershipTransferAuthorization {
	if x != nil {
		if x, ok := x.Payload.(*SignedFoundationRecord_OwnershipTransferAuthorization); ok {
			return x.OwnershipTransferAuthorization
		}
	}
	return nil
}

type isSignedFoundationRecord_Payload interface {
	isSignedFoundationRecord_Payload()
}

type SignedFoundationRecord_ProviderIdentity struct {
	ProviderIdentity *v11.ProviderIdentity `protobuf:"bytes,16,opt,name=provider_identity,json=providerIdentity,proto3,oneof"`
}

type SignedFoundationRecord_AgentIdentity struct {
	AgentIdentity *v11.AgentIdentity `protobuf:"bytes,17,opt,name=agent_identity,json=agentIdentity,proto3,oneof"`
}

type SignedFoundationRecord_HostIdentity struct {
	HostIdentity *v11.HostIdentity `protobuf:"bytes,18,opt,name=host_identity,json=hostIdentity,proto3,oneof"`
}

type SignedFoundationRecord_DeviceIdentity struct {
	DeviceIdentity *v11.DeviceIdentity `protobuf:"bytes,19,opt,name=device_identity,json=deviceIdentity,proto3,oneof"`
}

type SignedFoundationRecord_MinerIdentity struct {
	MinerIdentity *v11.MinerIdentity `protobuf:"bytes,20,opt,name=miner_identity,json=minerIdentity,proto3,oneof"`
}

type SignedFoundationRecord_RunnerIdentity struct {
	RunnerIdentity *v11.RunnerIdentity `protobuf:"bytes,21,opt,name=runner_identity,json=runnerIdentity,proto3,oneof"`
}

type SignedFoundationRecord_BuyerIdentity struct {
	BuyerIdentity *v11.BuyerIdentity `protobuf:"bytes,22,opt,name=buyer_identity,json=buyerIdentity,proto3,oneof"`
}

type SignedFoundationRecord_ServiceIdentity struct {
	ServiceIdentity *v11.ServiceIdentity `protobuf:"bytes,23,opt,name=service_identity,json=serviceIdentity,proto3,oneof"`
}

type SignedFoundationRecord_KeyLifecycle struct {
	KeyLifecycle *v11.KeyLifecycle `protobuf:"bytes,24,opt,name=key_lifecycle,json=keyLifecycle,proto3,oneof"`
}

type SignedFoundationRecord_PolicyBundle struct {
	PolicyBundle *v11.PolicyBundle `protobuf:"bytes,25,opt,name=policy_bundle,json=policyBundle,proto3,oneof"`
}

type SignedFoundationRecord_AuditEvent struct {
	AuditEvent *v11.AuditEvent `protobuf:"bytes,26,opt,name=audit_event,json=auditEvent,proto3,oneof"`
}

type SignedFoundationRecord_EvidenceRecord struct {
	EvidenceRecord *v11.EvidenceRecord `protobuf:"bytes,27,opt,name=evidence_record,json=evidenceRecord,proto3,oneof"`
}

type SignedFoundationRecord_ExperimentPlan struct {
	ExperimentPlan *v11.ExperimentPlan `protobuf:"bytes,28,opt,name=experiment_plan,json=experimentPlan,proto3,oneof"`
}

type SignedFoundationRecord_OwnershipTransferAuthorization struct {
	OwnershipTransferAuthorization *v11.OwnershipTransferAuthorization `protobuf:"bytes,29,opt,name=ownership_transfer_authorization,json=ownershipTransferAuthorization,proto3,oneof"`
}

func (*SignedFoundationRecord_ProviderIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_AgentIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_HostIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_DeviceIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_MinerIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_RunnerIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_BuyerIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_ServiceIdentity) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_KeyLifecycle) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_PolicyBundle) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_AuditEvent) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_EvidenceRecord) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_ExperimentPlan) isSignedFoundationRecord_Payload() {}

func (*SignedFoundationRecord_OwnershipTransferAuthorization) isSignedFoundationRecord_Payload() {}

var File_transport_v1_foundation_transport_proto protoreflect.FileDescriptor

const file_transport_v1_foundation_transport_proto_rawDesc = "" +
	"\n" +
	"'transport/v1/foundation_transport.proto\x12\x18cph.aiinfra.transport.v1\x1a\x16common/v1/common.proto\x1a\x1efoundation/v1/foundation.proto\"\x8d\v\n" +
	"\x16SignedFoundationRecord\x12T\n" +
	"\x0esigning_domain\x18\x01 \x01(\v2-.cph.aiinfra.common.v1.TransportSigningDomainR\rsigningDomain\x12D\n" +
	"\benvelope\x18\x02 \x01(\v2(.cph.aiinfra.common.v1.TransportEnvelopeR\benvelope\x12Z\n" +
	"\x11provider_identity\x18\x10 \x01(\v2+.cph.aiinfra.foundation.v1.ProviderIdentityH\x00R\x10providerIdentity\x12Q\n" +
	"\x0eagent_identity\x18\x11 \x01(\v2(.cph.aiinfra.foundation.v1.AgentIdentityH\x00R\ragentIdentity\x12N\n" +
	"\rhost_identity\x18\x12 \x01(\v2'.cph.aiinfra.foundation.v1.HostIdentityH\x00R\fhostIdentity\x12T\n" +
	"\x0fdevice_identity\x18\x13 \x01(\v2).cph.aiinfra.foundation.v1.DeviceIdentityH\x00R\x0edeviceIdentity\x12Q\n" +
	"\x0eminer_identity\x18\x14 \x01(\v2(.cph.aiinfra.foundation.v1.MinerIdentityH\x00R\rminerIdentity\x12T\n" +
	"\x0frunner_identity\x18\x15 \x01(\v2).cph.aiinfra.foundation.v1.RunnerIdentityH\x00R\x0erunnerIdentity\x12Q\n" +
	"\x0ebuyer_identity\x18\x16 \x01(\v2(.cph.aiinfra.foundation.v1.BuyerIdentityH\x00R\rbuyerIdentity\x12W\n" +
	"\x10service_identity\x18\x17 \x01(\v2*.cph.aiinfra.foundation.v1.ServiceIdentityH\x00R\x0fserviceIdentity\x12N\n" +
	"\rkey_lifecycle\x18\x18 \x01(\v2'.cph.aiinfra.foundation.v1.KeyLifecycleH\x00R\fkeyLifecycle\x12N\n" +
	"\rpolicy_bundle\x18\x19 \x01(\v2'.cph.aiinfra.foundation.v1.PolicyBundleH\x00R\fpolicyBundle\x12H\n" +
	"\vaudit_event\x18\x1a \x01(\v2%.cph.aiinfra.foundation.v1.AuditEventH\x00R\n" +
	"auditEvent\x12T\n" +
	"\x0fevidence_record\x18\x1b \x01(\v2).cph.aiinfra.foundation.v1.EvidenceRecordH\x00R\x0eevidenceRecord\x12T\n" +
	"\x0fexperiment_plan\x18\x1c \x01(\v2).cph.aiinfra.foundation.v1.ExperimentPlanH\x00R\x0eexperimentPlan\x12\x85\x01\n" +
	" ownership_transfer_authorization\x18\x1d \x01(\v29.cph.aiinfra.foundation.v1.OwnershipTransferAuthorizationH\x00R\x1eownershipTransferAuthorizationB\t\n" +
	"\apayloadJ\x04\b\x03\x10\x10BEZCgithub.com/cypherium/cypher/aiinfra/schema/transport/v1;transportv1b\x06proto3"

var (
	file_transport_v1_foundation_transport_proto_rawDescOnce sync.Once
	file_transport_v1_foundation_transport_proto_rawDescData []byte
)

func file_transport_v1_foundation_transport_proto_rawDescGZIP() []byte {
	file_transport_v1_foundation_transport_proto_rawDescOnce.Do(func() {
		file_transport_v1_foundation_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_v1_foundation_transport_proto_rawDesc), len(file_transport_v1_foundation_transport_proto_rawDesc)))
	})
	return file_transport_v1_foundation_transport_proto_rawDescData
}

var file_transport_v1_foundation_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_v1_foundation_transport_proto_goTypes = []any{
	(*SignedFoundationRecord)(nil),             // 0: cph.aiinfra.transport.v1.SignedFoundationRecord
	(*v1.TransportSigningDomain)(nil),          // 1: cph.aiinfra.common.v1.TransportSigningDomain
	(*v1.TransportEnvelope)(nil),               // 2: cph.aiinfra.common.v1.TransportEnvelope
	(*v11.ProviderIdentity)(nil),               // 3: cph.aiinfra.foundation.v1.ProviderIdentity
	(*v11.AgentIdentity)(nil),                  // 4: cph.aiinfra.foundation.v1.AgentIdentity
	(*v11.HostIdentity)(nil),                   // 5: cph.aiinfra.foundation.v1.HostIdentity
	(*v11.DeviceIdentity)(nil),                 // 6: cph.aiinfra.foundation.v1.DeviceIdentity
	(*v11.MinerIdentity)(nil),                  // 7: cph.aiinfra.foundation.v1.MinerIdentity
	(*v11.RunnerIdentity)(nil),                 // 8: cph.aiinfra.foundation.v1.RunnerIdentity
	(*v11.BuyerIdentity)(nil),                  // 9: cph.aiinfra.foundation.v1.BuyerIdentity
	(*v11.ServiceIdentity)(nil),                // 10: cph.aiinfra.foundation.v1.ServiceIdentity
	(*v11.KeyLifecycle)(nil),                   // 11: cph.aiinfra.foundation.v1.KeyLifecycle
	(*v11.PolicyBundle)(nil),                   // 12: cph.aiinfra.foundation.v1.PolicyBundle
	(*v11.AuditEvent)(nil),                     // 13: cph.aiinfra.foundation.v1.AuditEvent
	(*v11.EvidenceRecord)(nil),                 // 14: cph.aiinfra.foundation.v1.EvidenceRecord
	(*v11.ExperimentPlan)(nil),                 // 15: cph.aiinfra.foundation.v1.ExperimentPlan
	(*v11.OwnershipTransferAuthorization)(nil), // 16: cph.aiinfra.foundation.v1.OwnershipTransferAuthorization
}
var file_transport_v1_foundation_transport_proto_depIdxs = []int32{
	1,  // 0: cph.aiinfra.transport.v1.SignedFoundationRecord.signing_domain:type_name -> cph.aiinfra.common.v1.TransportSigningDomain
	2,  // 1: cph.aiinfra.transport.v1.SignedFoundationRecord.envelope:type_name -> cph.aiinfra.common.v1.TransportEnvelope
	3,  // 2: cph.aiinfra.transport.v1.SignedFoundationRecord.provider_identity:type_name -> cph.aiinfra.foundation.v1.ProviderIdentity
	4,  // 3: cph.aiinfra.transport.v1.SignedFoundationRecord.agent_identity:type_name -> cph.aiinfra.foundation.v1.AgentIdentity
	5,  // 4: cph.aiinfra.transport.v1.SignedFoundationRecord.host_identity:type_name -> cph.aiinfra.foundation.v1.HostIdentity
	6,  // 5: cph.aiinfra.transport.v1.SignedFoundationRecord.device_identity:type_name -> cph.aiinfra.foundation.v1.DeviceIdentity
	7,  // 6: cph.aiinfra.transport.v1.SignedFoundationRecord.miner_identity:type_name -> cph.aiinfra.foundation.v1.MinerIdentity
	8,  // 7: cph.aiinfra.transport.v1.SignedFoundationRecord.runner_identity:type_name -> cph.aiinfra.foundation.v1.RunnerIdentity
	9,  // 8: cph.aiinfra.transport.v1.SignedFoundationRecord.buyer_identity:type_name -> cph.aiinfra.foundation.v1.BuyerIdentity
	10, // 9: cph.aiinfra.transport.v1.SignedFoundationRecord.service_identity:type_name -> cph.aiinfra.foundation.v1.ServiceIdentity
	11, // 10: cph.aiinfra.transport.v1.SignedFoundationRecord.key_lifecycle:type_name -> cph.aiinfra.foundation.v1.KeyLifecycle
	12, // 11: cph.aiinfra.transport.v1.SignedFoundationRecord.policy_bundle:type_name -> cph.aiinfra.foundation.v1.PolicyBundle
	13, // 12: cph.aiinfra.transport.v1.SignedFoundationRecord.audit_event:type_name -> cph.aiinfra.foundation.v1.AuditEvent
	14, // 13: cph.aiinfra.transport.v1.SignedFoundationRecord.evidence_record:type_name -> cph.aiinfra.foundation.v1.EvidenceRecord
	15, // 14: cph.aiinfra.transport.v1.SignedFoundationRecord.experiment_plan:type_name -> cph.aiinfra.foundation.v1.ExperimentPlan
	16, // 15: cph.aiinfra.transport.v1.SignedFoundationRecord.ownership_transfer_authorization:type_name -> cph.aiinfra.foundation.v1.OwnershipTransferAuthorization
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_transport_v1_foundation_transport_proto_init() }
func file_transport_v1_foundation_transport_proto_init() {
	if File_transport_v1_foundation_transport_proto != nil {
		return
	}
	file_transport_v1_foundation_transport_proto_msgTypes[0].OneofWrappers = []any{
		(*SignedFoundationRecord_ProviderIdentity)(nil),
		(*SignedFoundationRecord_AgentIdentity)(nil),
		(*SignedFoundationRecord_HostIdentity)(nil),
		(*SignedFoundationRecord_DeviceIdentity)(nil),
		(*SignedFoundationRecord_MinerIdentity)(nil),
		(*SignedFoundationRecord_RunnerIdentity)(nil),
		(*SignedFoundationRecord_BuyerIdentity)(nil),
		(*SignedFoundationRecord_ServiceIdentity)(nil),
		(*SignedFoundationRecord_KeyLifecycle)(nil),
		(*SignedFoundationRecord_PolicyBundle)(nil),
		(*SignedFoundationRecord_AuditEvent)(nil),
		(*SignedFoundationRecord_EvidenceRecord)(nil),
		(*SignedFoundationRecord_ExperimentPlan)(nil),
		(*SignedFoundationRecord_OwnershipTransferAuthorization)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_v1_foundation_transport_proto_rawDesc), len(file_transport_v1_foundation_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_v1_foundation_transport_proto_goTypes,
		DependencyIndexes: file_transport_v1_foundation_transport_proto_depIdxs,
		MessageInfos:      file_transport_v1_foundation_transport_proto_msgTypes,
	}.Build()
	File_transport_v1_foundation_transport_proto = out.File
	file_transport_v1_foundation_transport_proto_goTypes = nil
	file_transport_v1_foundation_transport_proto_depIdxs = nil
}
