package consensus

import (
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/cypherium/cypher/common"
	"github.com/cypherium/cypher/core/types"
	"github.com/cypherium/cypher/crypto/bls"
	"github.com/cypherium/cypher/dex/checkpoint"
	"github.com/cypherium/cypher/dex/protocol"
	"github.com/cypherium/cypher/reconfig/hotstuff"
)

func TestGenerationCurrentIndependentGolden(t *testing.T) {
	// Independently generated by Python hashlib.sha256(label+b'\0'+payload).
	const wantPayload = `{"Version":4,"Generation":2}`
	const wantHash = "06d8f5c6afb82ed3a9e02e35152d9c21d289f611bbf9df47f789f6cadd4c69e9"
	b, h, err := envelopeBytes(generationPointer{4, 2}, "common-dex/storage-current/v4", 1024)
	if err != nil {
		t.Fatal(err)
	}
	var e walEnvelope
	if err = json.Unmarshal(b, &e); err != nil {
		t.Fatal(err)
	}
	if string(e.Payload) != wantPayload || hex.EncodeToString(h[:]) != wantHash {
		t.Fatalf("golden payload %s hash %x", e.Payload, h)
	}
	var p generationPointer
	if _, err = decodeEnvelopeBytes(b, "common-dex/storage-current/v4", &p); err != nil || p.Generation != 2 {
		t.Fatal(err)
	}
	if _, err = decodeEnvelopeBytes(append(b, ' '), "common-dex/storage-current/v4", &p); err == nil {
		t.Fatal("noncanonical envelope accepted")
	}
}

func generationNetwork(t *testing.T, height uint64) *network {
	return newConfiguredNetwork(t, height, func(c *Config) {
		c.StorageGenerations = true
		c.Execution = new(fixtureExecution)
		c.Actions = func(uint64) ([]byte, error) { return []byte{1}, nil }
	})
}

func TestGenerationRealFHS128BoundaryRestartAndOldState(t *testing.T) {
	n := generationNetwork(t, 130)
	n.start(t)
	for i, a := range n.nodes {
		if a.FinalizedHeight() != 129 || a.CertifiedHeight() != 130 || a.disk.Generation != 2 || a.disk.BaseHeight != 128 || len(a.disk.Records) > MaxRecords {
			t.Fatalf("node %d state %+v finalized=%d", i, a.StorageStatus(), a.FinalizedHeight())
		}
		before := hotstuff.CloneFHSSafetyState(a.disk.Safety)
		outbox := hotstuff.CloneSignedState(a.disk.Outbox)
		if err := a.Close(); err != nil {
			t.Fatal(err)
		}
		restored, err := Open(n.configs[i])
		if err != nil {
			t.Fatalf("node %d reopen: %v", i, err)
		}
		n.nodes[i] = restored
		if !reflect.DeepEqual(before, restored.disk.Safety) || !reflect.DeepEqual(outbox, restored.disk.Outbox) || restored.FinalizedHeight() != 129 {
			t.Fatal("generation restart changed own safety/finality")
		}
		for _, h := range []uint64{1, 63, 64, 65, 127, 128, 129} {
			state, err := restored.FinalizedState(h)
			if err != nil || len(state) != 8 || binary.BigEndian.Uint64(state) != h {
				t.Fatalf("old state %d %x err %v", h, state, err)
			}
			cp, proof, err := restored.FinalizedCheckpoint(h)
			if err != nil {
				t.Fatal(err)
			}
			if _, err = restored.epoch.Verify(cp, proof); err != nil {
				t.Fatal(err)
			}
		}
		if _, err := restored.ExportSnapshot(); err == nil {
			t.Fatal("incomplete archive advertised as standalone snapshot")
		}
	}
	// Two valid pending proposals exercise the same-view durable guard, rather
	// than only corrupt metadata or a view already below HighestQC.
	a := n.nodes[0]
	a.config.MaxHeight = 132
	n.configs[0].MaxHeight = 132
	parent := a.HighestCertified()
	id, err := hotstuff.SignedStateID(parent)
	if err != nil {
		t.Fatal(err)
	}
	view := a.CurrentN()
	context := hotstuff.FHSViewContext{Version: 3, ChainID: a.ChainID(), TargetView: view, KeyNumber: a.config.Domain.Epoch, KeyHash: common.Hash(a.config.Domain.EpochKey()), CommitteeHash: common.Hash(a.config.Domain.Committee), LeaderID: a.committee.List[(view-1)%7].Address, EntryKind: hotstuff.FHSViewFromQC}
	req := &hotstuff.FHSProposalBuildRequest{Key: hotstuff.FHSProposalBuildKey{ViewNumber: view, ViewID: context.ID(), LeaderID: context.LeaderID, ParentQCID: id.Hash()}, ParentQC: parent}
	var votes []*hotstuff.PersistedVote
	for _, action := range []byte{1, 2} {
		r, err := a.buildAction(req, []byte{action})
		if err != nil {
			t.Fatal(err)
		}
		extra, _ := encodeExtra(r)
		if err = a.OnPropose(r.Ref, extra, view, parent); err != nil {
			t.Fatal(err)
		}
		v, err := decodeRecordVote(r)
		if err != nil {
			t.Fatal(err)
		}
		votes = append(votes, v)
	}
	if err = a.PersistFHSVote(votes[0]); err != nil {
		t.Fatal(err)
	}
	a = reopenCompactSafetyNode(t, n, 0)
	if err = a.PersistFHSVote(votes[0]); err != nil {
		t.Fatal("exact pending vote", err)
	}
	if err = a.PersistFHSVote(votes[1]); err == nil || !strings.Contains(err.Error(), "conflicting durable DEX vote") {
		t.Fatal("same-view safety lost", err)
	}
	if err = a.Timeout(); !benign(err) && !strings.Contains(err.Error(), "transport unavailable") {
		t.Fatal(err)
	}
	before := hotstuff.CloneFHSSafetyState(a.disk.Safety)
	a = reopenCompactSafetyNode(t, n, 0)
	if !reflect.DeepEqual(before, a.disk.Safety) {
		t.Fatal("pending timeout lost across generation restart")
	}
	// Corruption tests close the sole reader/writer before changing fixture
	// bytes; every failed open must reject even with a recomputed checksum.
	if err = a.Close(); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(a.config.DataDir, "history", archiveName(64))
	original, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, kind := range []string{"missing", "corrupt", "recomputed_bad_state"} {
		t.Run(kind, func(t *testing.T) {
			switch kind {
			case "missing":
				if err := os.Remove(path); err != nil {
					t.Fatal(err)
				}
			case "corrupt":
				if err := os.WriteFile(path, []byte("broken"), 0600); err != nil {
					t.Fatal(err)
				}
			default:
				var e archiveEntry
				if _, err := decodeEnvelopeBytes(original, "common-dex/archive-entry/v4", &e); err != nil {
					t.Fatal(err)
				}
				e.Record.State[7] ^= 1
				b, _, err := envelopeBytes(e, "common-dex/archive-entry/v4", maxWALBytes)
				if err != nil {
					t.Fatal(err)
				}
				if err = os.WriteFile(path, b, 0600); err != nil {
					t.Fatal(err)
				}
			}
			if opened, err := Open(n.configs[0]); err == nil {
				opened.Close()
				t.Fatal("bad archive accepted")
			}
			if err := os.WriteFile(path, original, 0600); err != nil {
				t.Fatal(err)
			}
		})
	}
	statePath := filepath.Join(a.config.DataDir, generationStateName(a.disk.Generation))
	state, err := os.ReadFile(statePath)
	if err != nil {
		t.Fatal(err)
	}
	if err = os.Remove(statePath); err != nil {
		t.Fatal(err)
	}
	if opened, err := Open(n.configs[0]); err == nil {
		opened.Close()
		t.Fatal("CURRENT missing state fell back")
	}
	if err = os.WriteFile(statePath, state, 0600); err != nil {
		t.Fatal(err)
	}
	opened, err := Open(n.configs[0])
	if err != nil {
		t.Fatal(err)
	}
	n.nodes[0] = opened
}

func TestGenerationImmutableArchiveBudgetAndCurrentCorruption(t *testing.T) {
	w, err := openWAL(filepath.Join(t.TempDir(), "wal"))
	if err != nil {
		t.Fatal(err)
	}
	defer w.close()
	e := archiveEntry{Version: 4, Height: 1, Record: &Record{Checkpoint: protocol.Checkpoint{Sequence: 1}}}
	if _, _, err = w.writeArchive(e, archiveWorkReserve); !errors.Is(err, ErrStorageCapacity) {
		t.Fatal("quota not enforced", err)
	}
	h, n, err := w.writeArchive(e, minArchiveBudgetBytes)
	if err != nil {
		t.Fatal(err)
	}
	h2, n2, err := w.writeArchive(e, minArchiveBudgetBytes)
	if err != nil || h != h2 || n != n2 {
		t.Fatal("not idempotent", err)
	}
	e.Record.Action++
	if _, _, err = w.writeArchive(e, minArchiveBudgetBytes); err == nil {
		t.Fatal("immutable archive replaced")
	}
	if err = w.publishCurrent(2); err != nil {
		t.Fatal(err)
	}
	g, exists, err := w.loadCurrent()
	if err != nil || !exists || g != 2 {
		t.Fatal(err)
	}
	p := filepath.Join(w.dir, "CURRENT")
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	b[len(b)/2] ^= 1
	if err = os.WriteFile(p, b, 0600); err != nil {
		t.Fatal(err)
	}
	if _, _, err = w.loadCurrent(); err == nil {
		t.Fatal("corrupt CURRENT accepted")
	}
}

func TestGenerationCutFailurePublicationAndRestart(t *testing.T) {
	for _, stage := range []string{"archive-durable", "hot-durable", "current-durable"} {
		t.Run(stage, func(t *testing.T) {
			n := generationNetwork(t, 66)
			injected := errors.New("injected generation boundary")
			a := n.nodes[0]
			a.wal.generationFault = func(s string) error {
				if s == stage {
					return injected
				}
				return nil
			}
			for _, node := range n.nodes {
				if err := node.Start(); !benign(err) {
					t.Fatal(err)
				}
			}
			// Same actual FHS transport as network.pump, but stop precisely on
			// this node's selected persistence failure instead of hiding it.
			failed := false
			for step := 0; step < 20000 && !failed; step++ {
				for _, node := range n.nodes {
					_, err := node.Advance()
					if err != nil && !benign(err) {
						if node == a && errors.Is(err, injected) {
							failed = true
							break
						}
						t.Fatal(err)
					}
				}
				if failed {
					break
				}
				if len(n.queue) == 0 {
					continue
				}
				d := n.queue[0]
				n.queue = n.queue[1:]
				for _, node := range n.nodes {
					if node.Self() == d.to {
						err := node.Handle(d.message)
						if err != nil && !benign(err) {
							if node == a && errors.Is(err, injected) {
								failed = true
							} else {
								t.Fatal(err)
							}
						}
						break
					}
				}
			}
			if !failed || a.fatal == nil {
				t.Fatal("fault boundary not reached")
			}
			vote := hotstuff.ClonePersistedVote(a.disk.Safety.LastVote)
			if err := a.Close(); err != nil {
				t.Fatal(err)
			}
			restored, err := Open(n.configs[0])
			if err != nil {
				t.Fatal("restart", err)
			}
			n.nodes[0] = restored
			if !reflect.DeepEqual(vote, restored.disk.Safety.LastVote) {
				t.Fatal("latest own vote lost at cut")
			}
			if stage == "current-durable" && restored.disk.BaseHeight != 64 {
				t.Fatal("published cut rolled back")
			}
			if stage != "current-durable" && restored.disk.BaseHeight != 0 {
				t.Fatal("unpublished cut trusted")
			}
			restored.SetTransport(n.send)
			// The interrupted node may have only QC64 while peers already have
			// QC65. Repair with the normal authenticated proposal-data path
			// before delivering their queued later-view messages.
			for _, peer := range n.nodes[1:] {
				data, err := peer.CertifiedData(restored.CertifiedHeight(), 8)
				if err != nil {
					t.Fatal(err)
				}
				for _, raw := range data {
					if err = restored.ImportProposalData(raw); err != nil {
						t.Fatal("authenticated crash catch-up", err)
					}
				}
			}
			if err = restored.Start(); !benign(err) {
				t.Fatal(err)
			}
			n.pump(t)
			if restored.FinalizedHeight() < 64 || restored.disk.BaseHeight != 64 {
				t.Fatal("failed to resume authenticated cut")
			}
		})
	}
}

func TestGenerationLegacyWALNotReinterpreted(t *testing.T) {
	n := newNetwork(t, 3)
	n.start(t)
	a := n.nodes[0]
	if err := a.Close(); err != nil {
		t.Fatal(err)
	}
	c := n.configs[0]
	c.StorageGenerations = true
	if opened, err := Open(c); err == nil {
		opened.Close()
		t.Fatal("legacy format silently adopted")
	}
}

func TestGenerationCapacityBackpressureKeepsStateAndResumes(t *testing.T) {
	n := generationNetwork(t, 5)
	n.start(t)
	a := n.nodes[0]
	before := hotstuff.CloneFHSSafetyState(a.disk.Safety)
	want, err := a.FinalizedState(4)
	if err != nil {
		t.Fatal(err)
	}
	// This is a separate small-threshold component fixture. The 130-height
	// test above uses the actual production 64-height interval unchanged.
	a.wal.rotationInterval = 2
	a.config.ArchiveBudgetBytes = archiveWorkReserve + 1
	if err = a.MaintainStorage(); !errors.Is(err, ErrStorageCapacity) {
		t.Fatal("capacity not signalled", err)
	}
	if !a.storageBlocked || a.disk.BaseHeight != 0 || a.FinalizedHeight() != 4 || !reflect.DeepEqual(before, a.disk.Safety) {
		t.Fatal("capacity erased state or safety")
	}
	got, err := a.FinalizedState(4)
	if err != nil || string(got) != string(want) {
		t.Fatal("old obligation lost", err)
	}
	if err = a.ScheduleFHSProposalBuild(&hotstuff.FHSProposalBuildRequest{}); !errors.Is(err, ErrStorageCapacity) {
		t.Fatal("new proposal not paused", err)
	}
	a.config.ArchiveBudgetBytes = DefaultArchiveBudgetBytes
	if err = a.MaintainStorage(); err != nil {
		t.Fatal("resume", err)
	}
	if a.storageBlocked || a.disk.BaseHeight != 2 || a.FinalizedHeight() != 4 || !reflect.DeepEqual(before, a.disk.Safety) {
		t.Fatal("bad resumed state")
	}
	if err = a.MaintainStorage(); err != nil {
		t.Fatal(err)
	}
	if a.disk.BaseHeight != 4 || a.disk.Generation != 2 {
		t.Fatal("small fixture did not rotate twice")
	}
	a = reopenCompactSafetyNode(t, n, 0)
	got, err = a.FinalizedState(4)
	if err != nil || string(got) != string(want) || !reflect.DeepEqual(before, a.disk.Safety) {
		t.Fatal("resumed cold state mismatch", err)
	}
}

// Authentication fixture only: real registered test keys sign the complete
// context. This is not a claim that the alternate history ran on a live network.
func generationFixtureQC(t *testing.T, n *network, r *Record) *hotstuff.SignedState {
	return generationFixtureQCMask(t, n, r, 31)
}

func generationFixtureQCMask(t *testing.T, n *network, r *Record, mask byte) *hotstuff.SignedState {
	t.Helper()
	ref, err := types.DecodeHotstuffProposalRef(r.Ref)
	if err != nil {
		t.Fatal(err)
	}
	var agg *bls.Sign
	for i := 0; i < 7; i++ {
		if mask&(1<<i) == 0 {
			continue
		}
		s := n.configs[i].Secret
		sig, err := hotstuff.SignFHSSignatureWithContext(s, s.GetPublicKey(), r.Ref, ref.ChainID, hotstuff.MsgVotePrepare, ref.ViewID, ref.LeaderID)
		if err != nil {
			t.Fatal(err)
		}
		if agg == nil {
			agg = sig
		} else {
			agg.Add(sig)
		}
	}
	return &hotstuff.SignedState{State: r.Ref, Sign: agg.Serialize(), Mask: []byte{mask}, ViewID: ref.ViewID, LeaderID: ref.LeaderID, Number: ref.ViewNumber}
}

func TestGenerationTailRecoveryAcceptsAlternateAuthenticatedQC(t *testing.T) {
	n := generationNetwork(t, 5)
	n.start(t)
	a := n.nodes[0]
	a.wal.rotationInterval = 2
	a.wal.generationFault = func(stage string) error {
		if stage == "archive-durable" {
			return errors.New("injected before hot publication")
		}
		return nil
	}
	if err := a.MaintainStorage(); err == nil {
		t.Fatal("selected crash boundary did not fail")
	}
	path := filepath.Join(a.config.DataDir, "history", archiveName(2))
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	a = reopenCompactSafetyNode(t, n, 0)
	if a.disk.BaseHeight != 0 {
		t.Fatal("unpublished archive promoted")
	}
	e, _, _, err := a.wal.readArchive(2)
	if err != nil {
		t.Fatal(err)
	}
	proof, err := checkpoint.DecodeProof(e.Finalized.Proof)
	if err != nil || len(proof.Descendants) == 0 {
		t.Fatal("fixture proof", err)
	}
	mask := byte(31)
	if len(proof.Descendants[0].Mask) == 1 && proof.Descendants[0].Mask[0] == mask {
		mask = 62
	}
	proof.Descendants[0] = generationFixtureQCMask(t, n, &Record{Ref: proof.Descendants[0].State}, mask)
	e.Finalized.Proof, err = checkpoint.EncodeProof(proof)
	if err != nil {
		t.Fatal(err)
	}
	if err = a.verifyArchivedFinality(e); err != nil {
		t.Fatal("alternate subset must authenticate", err)
	}
	for _, kind := range []string{"state", "previous", "proof"} {
		b, _ := json.Marshal(e)
		var bad archiveEntry
		if err := json.Unmarshal(b, &bad); err != nil {
			t.Fatal(err)
		}
		switch kind {
		case "state":
			bad.Record.State[0] ^= 1
		case "previous":
			bad.Previous[0] ^= 1
		case "proof":
			bad.Finalized.Proof[len(bad.Finalized.Proof)-1] ^= 1
		}
		if _, _, err = a.reuseOrWriteArchive(bad); err == nil {
			t.Fatal("conflicting tail reused", kind)
		}
	}
	// A valid alternate descendant certificate may arrive from another peer
	// after the crash. It proves the same finalized checkpoint. The old durable
	// proof remains immutable and must be authenticated before being reused.
	a.disk.Finalized[1].Proof = e.Finalized.Proof
	a.wal.rotationInterval = 2
	if err = a.MaintainStorage(); err != nil {
		t.Fatal(err)
	}
	after, err := os.ReadFile(path)
	if err != nil || string(before) != string(after) || a.disk.BaseHeight != 2 {
		t.Fatal("immutable tail changed or cut failed", err)
	}
	beforeSafety := hotstuff.CloneFHSSafetyState(a.disk.Safety)
	a = reopenCompactSafetyNode(t, n, 0)
	if !reflect.DeepEqual(beforeSafety, a.disk.Safety) || a.disk.BaseHeight != 2 {
		t.Fatal("alternate proof recovery lost safety")
	}
	state, err := a.FinalizedState(2)
	if err != nil || binary.BigEndian.Uint64(state) != 2 {
		t.Fatal("old state lost", err)
	}
}

func generationPendingRecord(t *testing.T, a *Application, parent *hotstuff.SignedState, view uint64, action byte) *Record {
	t.Helper()
	id, err := hotstuff.SignedStateID(parent)
	if err != nil {
		t.Fatal(err)
	}
	c := hotstuff.FHSViewContext{Version: 3, ChainID: a.ChainID(), TargetView: view, KeyNumber: a.config.Domain.Epoch, KeyHash: common.Hash(a.config.Domain.EpochKey()), CommitteeHash: common.Hash(a.config.Domain.Committee), LeaderID: a.committee.List[(view-1)%7].Address, EntryKind: hotstuff.FHSViewFromQC}
	req := &hotstuff.FHSProposalBuildRequest{Key: hotstuff.FHSProposalBuildKey{ViewNumber: view, ViewID: c.ID(), LeaderID: c.LeaderID, ParentQCID: id.Hash()}, ParentQC: parent}
	r, err := a.buildAction(req, []byte{action})
	if err != nil {
		t.Fatal(err)
	}
	return r
}

func TestGenerationOwnOrphanVoteRetainsNoncanonicalParent(t *testing.T) {
	n := generationNetwork(t, 5)
	n.dropped[n.nodes[1].Self()] = true
	n.dropped[n.nodes[2].Self()] = true
	n.start(t)
	for missed := 0; missed < 2; missed++ {
		for _, a := range n.nodes {
			if !n.dropped[a.Self()] {
				if err := a.Timeout(); !benign(err) {
					t.Fatal(err)
				}
			}
		}
		n.pump(t)
	}
	if n.nodes[0].FinalizedHeight() != 4 {
		t.Fatal("real FHS skipped-leader history incomplete")
	}
	a := n.nodes[1]
	raw, err := n.nodes[0].LatestCertifiedData(1)
	if err != nil {
		t.Fatal(err)
	}
	if err = a.ImportProposalData(raw); err != nil {
		t.Fatal(err)
	}
	// A valid older QC at height2/view2, then this node's sole pending vote
	// at height3/view3. The actual five-node branch uses height2/view4.
	parent := generationPendingRecord(t, a, a.HighestCertified(), 2, 2)
	parent.QC = generationFixtureQC(t, n, parent)
	if err = a.storeRecord(parent); err != nil {
		t.Fatal(err)
	}
	if err = a.OnCertified(parent.QC); err != nil {
		t.Fatal(err)
	}
	orphan := generationPendingRecord(t, a, parent.QC, 3, 1)
	extra, _ := encodeExtra(orphan)
	if err = a.OnPropose(orphan.Ref, extra, 3, parent.QC); err != nil {
		t.Fatal(err)
	}
	vote, err := decodeRecordVote(orphan)
	if err != nil {
		t.Fatal(err)
	}
	if err = a.PersistFHSVote(vote); err != nil {
		t.Fatal(err)
	}
	data, err := n.nodes[0].CertifiedData(1, 8)
	if err != nil {
		t.Fatal(err)
	}
	for _, raw := range data {
		if err = a.ImportProposalData(raw); err != nil {
			t.Fatal(err)
		}
	}
	a.wal.rotationInterval = 2
	if err = a.MaintainStorage(); err != nil {
		t.Fatal(err)
	}
	if err = a.MaintainStorage(); err != nil {
		t.Fatal(err)
	}
	pref, _ := types.DecodeHotstuffProposalRef(parent.Ref)
	if a.disk.BaseHeight != 4 || a.disk.Records[pref.ProposalID().Hex()] == nil {
		t.Fatal("old noncanonical vote parent was pruned")
	}
	a = reopenCompactSafetyNode(t, n, 1)
	if !reflect.DeepEqual(vote, a.disk.Safety.LastVote) || a.FinalizedHeight() != 4 {
		t.Fatal("old own vote lost or changed")
	}
	if a.recordForQC(parent.QC) == nil {
		t.Fatal("noncanonical parent missing after cold replay")
	}
}

func TestLatestCertifiedDataSelectsHighestViewWithinBound(t *testing.T) {
	n := generationNetwork(t, 5)
	n.start(t)
	a := n.nodes[0]
	a.config.MaxHeight = 6
	parent := a.HighestCertified()
	for view := uint64(6); view <= 15; view++ {
		r := generationPendingRecord(t, a, parent, view, byte(view))
		r.QC = generationFixtureQC(t, n, r)
		if err := a.storeRecord(r); err != nil {
			t.Fatal(err)
		}
	}
	// A conflicting lower view must not make the highest-view query depend on
	// map iteration order. This is synthetic hostile certificate data, not a
	// claim that honest FHS validators produce two quorums for the same view.
	lower := generationPendingRecord(t, a, parent, 6, 98)
	lower.QC = generationFixtureQC(t, n, lower)
	if err := a.storeRecord(lower); err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 64; i++ {
		raw, err := a.LatestCertifiedData(6)
		var selected Record
		if err != nil || json.Unmarshal(raw, &selected) != nil || selected.QC.Number != 15 {
			t.Fatal("lower-view conflict changed highest-view query", err)
		}
	}
	raw, err := a.LatestCertifiedData(6)
	if err != nil {
		t.Fatal(err)
	}
	var r Record
	if err = json.Unmarshal(raw, &r); err != nil || r.QC.Number != 15 {
		t.Fatal("highest view absent", err)
	}
	if _, err = a.LatestCertifiedData(0); !errors.Is(err, ErrUnavailable) {
		t.Fatal("zero height")
	}
	if _, err = a.LatestCertifiedData(7); !errors.Is(err, ErrUnavailable) {
		t.Fatal("out of budget")
	}
	other := generationPendingRecord(t, a, parent, 15, 99)
	other.QC = generationFixtureQC(t, n, other)
	if err = a.storeRecord(other); err != nil {
		t.Fatal(err)
	}
	if _, err = a.LatestCertifiedData(6); err == nil {
		t.Fatal("conflicting same-view QC hidden")
	}
}
