package clxevidence_test

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"math/big"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strconv"
	"testing"

	"github.com/cypherium/cypher/common"
	"github.com/cypherium/cypher/core/state"
	"github.com/cypherium/cypher/core/types"
	"github.com/cypherium/cypher/crypto/bls"
	"github.com/cypherium/cypher/dex/checkpoint"
	"github.com/cypherium/cypher/dex/clxevidence"
	"github.com/cypherium/cypher/dex/protocol"
	"github.com/cypherium/cypher/dex/relay"
	"github.com/cypherium/cypher/dex/relay/source"
	"github.com/cypherium/cypher/dex/settlement"
	"github.com/cypherium/cypher/reconfig/bftview"
	"github.com/cypherium/cypher/reconfig/hotstuff"
	"github.com/cypherium/cypher/rlp"
)

// These tests use actual HTTP and cryptographic CLX/DEX proofs generated by unit
// fixtures. They do not assert actual-process financial execution or settlement.
type plannerNoSigner struct{}

func (plannerNoSigner) Sign(context.Context, common.Address, *types.Transaction, *big.Int) (*types.Transaction, error) {
	return nil, errors.New("planner test cannot send native transactions")
}

func plannerDomain(f *clxevidence.RollingFinancialFixture) protocol.Domain {
	nodes := make([]*common.Cnode, 7)
	for i := range nodes {
		n := f.Config.ChainConfig.DEXDevnet.Committee[i]
		nodes[i] = &n
	}
	return protocol.Domain{Version: 1, ChainID: f.Config.ChainID, Genesis: protocol.Hash(f.Config.Genesis.Hash()), DEXID: f.Config.DEXID, Epoch: 1, Committee: protocol.Hash((&bftview.Committee{List: nodes}).RlpHash())}
}

func plannerQC(t *testing.T, ref *types.HotstuffProposalRef) *hotstuff.SignedState {
	t.Helper()
	raw := ref.EncodeToBytes()
	var aggregate *bls.Sign
	for i := 0; i < 5; i++ {
		var key bls.SecretKey
		if err := key.SetDecString(fmt.Sprint(1200 + i)); err != nil {
			t.Fatal(err)
		}
		sig, err := hotstuff.SignFHSSignatureWithContext(&key, key.GetPublicKey(), raw, ref.ChainID, hotstuff.MsgVotePrepare, ref.ViewID, ref.LeaderID)
		if err != nil {
			t.Fatal(err)
		}
		if aggregate == nil {
			aggregate = sig
		} else {
			aggregate.Add(sig)
		}
	}
	return &hotstuff.SignedState{State: raw, Sign: aggregate.Serialize(), Mask: []byte{31}, ViewID: ref.ViewID, LeaderID: ref.LeaderID, Number: ref.ViewNumber}
}

type plannerRange struct {
	height, start, end uint64
	badRoot            bool
}

func plannerBundles(t *testing.T, f *clxevidence.RollingFinancialFixture, ranges []plannerRange, mutate ...func(*protocol.Checkpoint)) [][]byte {
	t.Helper()
	domain := plannerDomain(f)
	pre, err := protocol.NativeGenesisRootV3(protocol.Hash(f.Config.ChainConfig.DEXDevnet.GenesisSeed), domain, [20]byte(f.Config.Custody))
	if err != nil {
		t.Fatal(err)
	}
	var previous protocol.Hash
	var out [][]byte
	for i, r := range ranges {
		seq := uint64(i + 1)
		finance := protocol.FinanceSummary{Version: 1, Domain: domain, Custody: [20]byte(f.Config.Custody), Sequence: seq}
		funding, err := finance.Hash()
		if err != nil {
			t.Fatal(err)
		}
		root, err := protocol.InboxEntriesRoot(f.Entries[r.height][r.start:r.end])
		if err != nil {
			t.Fatal(err)
		}
		if r.badRoot {
			root[0] ^= 1
		}
		cp := protocol.Checkpoint{Version: 1, ProofMode: 1, ChainID: domain.ChainID, Genesis: domain.Genesis, DEXID: domain.DEXID, Epoch: domain.Epoch, Committee: domain.Committee, Sequence: seq, Previous: previous, PreRoot: pre, PostRoot: protocol.Hash{9, byte(seq)}, FirstBlock: seq, LastBlock: seq, CLXHeight: r.height, CLXHash: protocol.Hash(f.Blocks[r.height-1].Hash()), InboxStart: r.start, InboxEnd: r.end, InboxRoot: root, DataRoot: protocol.Hash{8, byte(seq)}, DataSchema: 4, FundingRef: funding}
		for _, modify := range mutate {
			modify(&cp)
		}
		hash, err := cp.Hash()
		if err != nil {
			t.Fatal(err)
		}
		refs := make([]*types.HotstuffProposalRef, 2)
		qcs := make([]*hotstuff.SignedState, 2)
		for j := range refs {
			view := seq + uint64(j)
			node := f.Config.ChainConfig.DEXDevnet.Committee[(view-1)%7]
			ref := &types.HotstuffProposalRef{Version: types.HotstuffProposalRefVersion, ChainID: domain.ChainID, Number: view, ViewNumber: view, ViewID: common.Hash{byte(view), 42}, LeaderID: bftview.GetNodeID(node.Address, node.Public), BlockHash: common.Hash(hash), ParentHash: common.Hash{99}, StateRoot: common.Hash(cp.PostRoot), BodyHash: common.Hash(cp.DataRoot), BodySize: 8, ExtraHash: types.HotstuffProposalExtraHash(nil), KeyHash: common.Hash(domain.EpochKey()), Time: view}
			if j > 0 {
				id, _ := hotstuff.SignedStateID(qcs[j-1])
				ref.ParentQCID, ref.ParentHash, ref.BlockHash = id.Hash(), refs[j-1].BlockHash, common.Hash{44, byte(view)}
			}
			refs[j], qcs[j] = ref, plannerQC(t, ref)
		}
		proof, err := checkpoint.EncodeProof(checkpoint.Proof{Target: qcs[0], Descendants: qcs[1:]})
		if err != nil {
			t.Fatal(err)
		}
		bundle, err := checkpoint.BuildSettlementBundle(cp, proof, finance, nil, nil)
		if err != nil {
			t.Fatal(err)
		}
		raw, err := checkpoint.EncodeSettlementBundle(bundle)
		if err != nil {
			t.Fatal(err)
		}
		out = append(out, raw)
		pre, previous = cp.PostRoot, hash
	}
	return out
}

func plannerNetwork(t *testing.T, s *sourceFixtureHTTP, bundles *[][]byte) (*relay.Network, relay.Config, relay.NetworkConfig) {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/v1/status":
			json.NewEncoder(w).Encode(map[string]interface{}{"Finalized": len(*bundles)})
		case "/v1/settlement":
			h, err := strconv.Atoi(r.URL.Query().Get("height"))
			if err != nil || h < 1 || h > len(*bundles) {
				http.Error(w, "unavailable", 404)
				return
			}
			json.NewEncoder(w).Encode(map[string]interface{}{"Bytes": (*bundles)[h-1]})
		default:
			http.Error(w, "test never submits", 400)
		}
	}))
	t.Cleanup(server.Close)
	cfg := relay.Config{Devnet: true, Domain: plannerDomain(s.f), Custody: s.f.Config.Custody, Payers: map[relay.Lane]common.Address{relay.Anchor: {19: 91}, relay.Checkpoint: {19: 92}, relay.Claim: {19: 93}}, GasLimits: map[relay.Lane]uint64{relay.Anchor: 1000000, relay.Checkpoint: 1000000, relay.Claim: 1000000}, GasPrice: big.NewInt(1), MaxGasCost: big.NewInt(1000000)}
	dir := filepath.Join(t.TempDir(), "source")
	networkCfg := relay.NetworkConfig{Relay: cfg, Source: source.Config{Dir: dir, Endpoint: s.server.URL, CLX: s.f.Config}, SubmitURL: server.URL, DEXURL: server.URL, MaxHeight: 128, AutoInbox: true}
	n, err := relay.OpenNetwork(networkCfg)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { n.Close() })
	for n.Source.Current().Height < s.head {
		if _, err = n.Source.Advance(context.Background()); err != nil {
			t.Fatal(err)
		}
	}
	return n, cfg, networkCfg
}

func plannerInboxJob(t *testing.T, n *relay.Network, cfg relay.Config, f *clxevidence.RollingFinancialFixture, baseHeight, height, start, end uint64) relay.Job {
	t.Helper()
	base, err := f.Verifier.BootstrapAnchor()
	if baseHeight > 0 {
		base, err = n.Source.AnchorAt(context.Background(), baseHeight, protocol.Hash(f.Blocks[baseHeight-1].Hash()))
	}
	if err != nil {
		t.Fatal(err)
	}
	entries := f.Entries[height][start:end]
	e, target, err := n.Source.BuildRange(context.Background(), base, height, start, entries)
	if err != nil {
		t.Fatal(err)
	}
	raw, err := clxevidence.EncodeRollingEvidence(e)
	if err != nil {
		t.Fatal(err)
	}
	key, _ := target.ID()
	if len(entries) != 0 {
		root, _ := protocol.InboxEntriesRoot(entries)
		var b [48]byte
		binary.BigEndian.PutUint64(b[:8], start)
		binary.BigEndian.PutUint64(b[8:16], end)
		copy(b[16:], root[:])
		key = protocol.Digest("common-dex/relay-inbox-key/v1", b[:])
	}
	auth, _ := target.Encode()
	return relay.Job{Version: 1, Lane: relay.Inbox, ID: relay.BusinessID(cfg.Domain, cfg.Custody, relay.Inbox, key), Payload: append([]byte("CDXA"), raw...), Authorization: auth}
}

func plannerCheckJob(t *testing.T, n *relay.Network, cfg relay.Config, job relay.Job, want string) relay.Record {
	t.Helper()
	r, err := relay.Open(filepath.Join(t.TempDir(), "relay"), cfg, n, plannerNoSigner{})
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	if err = r.Enqueue(job); err != nil {
		t.Fatal(err)
	}
	if err = r.Step(context.Background()); err != nil {
		t.Fatal(err)
	}
	record := r.Status()[0]
	if record.Phase != want {
		t.Fatalf("phase=%s want=%s error=%s", record.Phase, want, record.LastError)
	}
	return record
}

func TestRelayPlannerSemanticInboxCompletion(t *testing.T) {
	s := newSourceHTTP(t, 100)
	for _, tc := range []struct {
		name                 string
		ranges               []plannerRange
		base, height, lo, hi uint64
		want                 string
	}{
		{"empty_equivalent_proof", []plannerRange{{16, 0, 0, false}, {32, 0, 0, false}}, 0, 32, 0, 0, "complete"},
		{"empty_authenticated_descendant", []plannerRange{{100, 0, 0, false}}, 64, 80, 0, 0, "complete"},
		{"split_range", []plannerRange{{1, 0, 1, false}, {1, 1, 3, false}}, 0, 1, 0, 3, "complete"},
		{"broader_range", []plannerRange{{1, 0, 3, false}}, 0, 1, 1, 2, "complete"},
		{"broader_right", []plannerRange{{65, 0, 4, false}}, 0, 1, 0, 3, "complete"},
		{"bad_authenticated_root", []plannerRange{{1, 0, 3, true}}, 0, 1, 0, 3, "nonce_conflict"},
		{"bad_broader_root", []plannerRange{{1, 0, 3, true}}, 0, 1, 1, 2, "nonce_conflict"},
		{"cursor_gap_is_not_completion", []plannerRange{{1, 2, 3, false}}, 0, 1, 0, 3, "waiting"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			bundles := plannerBundles(t, s.f, tc.ranges)
			n, cfg, _ := plannerNetwork(t, s, &bundles)
			job := plannerInboxJob(t, n, cfg, s.f, tc.base, tc.height, tc.lo, tc.hi)
			record := plannerCheckJob(t, n, cfg, job, tc.want)
			if tc.want == "complete" {
				var forensic struct {
					Anchor []byte
					Paths  [][]byte
					DEX    []byte
				}
				var included struct {
					Version uint16
					Bundles [][]byte
				}
				if err := rlp.DecodeBytes(record.Proof, &forensic); err != nil {
					t.Fatal(err)
				}
				if err := rlp.DecodeBytes(forensic.DEX, &included); err != nil || included.Version != 1 {
					t.Fatal("completion forensic bundle codec", err)
				}
				wantCount := len(tc.ranges)
				if tc.lo == tc.hi {
					wantCount = 1
				}
				if len(included.Bundles) != wantCount || len(record.Proof) > clxevidence.MaxEvidenceBytes {
					t.Fatal("consumed range proof omitted or unbounded")
				}
				if (tc.name == "broader_range" || tc.name == "broader_right") && len(forensic.Paths) == 0 {
					t.Fatal("broader range MPT evidence omitted")
				}
			}
		})
	}
}

func TestRelayPlannerEmptyAnchorConflict(t *testing.T) {
	s := newSourceHTTP(t, 3)
	for _, height := range []uint64{1, 3} {
		t.Run(strconv.FormatUint(height, 10), func(t *testing.T) {
			bundles := plannerBundles(t, s.f, []plannerRange{{height, 0, 0, false}}, func(cp *protocol.Checkpoint) { cp.CLXHash[0] ^= 1 })
			n, cfg, _ := plannerNetwork(t, s, &bundles)
			job := plannerInboxJob(t, n, cfg, s.f, 0, 1, 0, 0)
			r, err := relay.Open(filepath.Join(t.TempDir(), "relay"), cfg, n, plannerNoSigner{})
			if err != nil {
				t.Fatal(err)
			}
			defer r.Close()
			if err = r.Enqueue(job); err != nil {
				t.Fatal(err)
			}
			err = r.Step(context.Background())
			status := r.Status()[0]
			if status.Phase == "complete" || status.LastError == "" {
				t.Fatal("foreign empty target treated as completion")
			}
			if height == 1 && (err != nil || status.Phase != "nonce_conflict") {
				t.Fatal("exact-height authenticated conflict not exposed", err)
			}
			if height > 1 && !errors.Is(err, source.ErrAuthentication) {
				t.Fatal("descendant was not authenticated against source chain", err)
			}
		})
	}
}

func TestRelayPlannerHistoricalLegBeyondSourceRequest(t *testing.T) {
	requireSourceNetwork(t)
	f := clxevidence.RollingPlannerFixtureForTest(t, 65, func(height uint64, db *state.StateDB, f *clxevidence.RollingFinancialFixture) {
		db.SetNonce(f.Config.Custody, 1)
		if height != 35 {
			return
		}
		a, err := f.Verifier.BootstrapAnchor()
		if err != nil {
			t.Fatal(err)
		}
		a.Height, a.BlockHash, a.StateRoot, a.InboxCount = 34, protocol.Hash(f.Blocks[33].Hash()), protocol.Hash(f.Blocks[33].Root()), 3
		raw, _ := a.Encode()
		padded := make([]byte, 256)
		copy(padded, raw)
		keys, _ := settlement.RollingAnchorStorageKeys(34)
		for i := 0; i < 8; i++ {
			db.SetState(f.Config.Custody, keys[i], common.BytesToHash(padded[i*32:(i+1)*32]))
		}
		id, _ := a.ID()
		db.SetState(f.Config.Custody, keys[8], common.Hash(id))
		db.SetState(f.Config.Custody, settlement.RollingAnchorIDStorageKey(id), common.BigToHash(big.NewInt(34)))
		var meta common.Hash
		binary.BigEndian.PutUint64(meta[:8], 34)
		binary.BigEndian.PutUint64(meta[8:16], 34)
		binary.BigEndian.PutUint64(meta[16:24], 1)
		db.SetState(f.Config.Custody, settlement.RollingMetadataStorageKey(), meta)
	})
	s := &sourceFixtureHTTP{f: f, head: 65}
	s.server = httptest.NewServer(http.HandlerFunc(s.serve))
	t.Cleanup(s.server.Close)
	for _, height := range []uint64{1, 33} {
		t.Run(strconv.FormatUint(height, 10), func(t *testing.T) {
			bundles := plannerBundles(t, f, []plannerRange{{height, 0, 0, false}})
			n, cfg, _ := plannerNetwork(t, s, &bundles)
			r, err := relay.Open(filepath.Join(t.TempDir(), "relay"), cfg, n, plannerNoSigner{})
			if err != nil {
				t.Fatal(err)
			}
			defer r.Close()
			discoveryErr := n.Discover(context.Background(), r) // source caught-up is explicit unavailable.
			var found bool
			for _, record := range r.Status() {
				if record.Job.Lane != relay.Anchor {
					continue
				}
				found = true
				if len(record.Job.Payload) > protocol.MaxNativeCallBytes {
					t.Fatal("historical native byte bound expanded")
				}
				call, err := protocol.DecodeNativeCall(record.Job.Payload)
				if err != nil {
					t.Fatal(err)
				}
				e, continuation, err := settlement.DecodeAnchorUpdate(call.Body)
				if err != nil || len(e.Headers)+len(continuation) != 34 {
					t.Fatal("historical legs missing", err)
				}
				base, _ := f.Verifier.BootstrapAnchor()
				_, target, err := f.Verifier.VerifyRolling(base, 0, e)
				if err != nil || target.Height != height {
					t.Fatal("historical target", err)
				}
				last, err := f.Verifier.VerifyHeaderWitnesses(target, continuation)
				if err != nil || last.Number.Uint64() != 34 {
					t.Fatal("historical retained descendant", err)
				}
			}
			if !found {
				t.Fatal("bounded historical anchor not planned", discoveryErr)
			}
		})
	}
}

func TestRelayPlannerColdSourceAndRepeatedInboxCompletion(t *testing.T) {
	s := newSourceHTTP(t, 100)
	bundles := plannerBundles(t, s.f, []plannerRange{{32, 0, 3, false}, {96, 3, 3, false}, {96, 3, 4, false}})
	n, cfg, networkCfg := plannerNetwork(t, s, &bundles)
	first := plannerInboxJob(t, n, cfg, s.f, 0, 1, 0, 3)
	empty := plannerInboxJob(t, n, cfg, s.f, 64, 80, 3, 3)
	later := plannerInboxJob(t, n, cfg, s.f, 64, 65, 3, 4)
	dir := filepath.Join(t.TempDir(), "relay")
	r, err := relay.Open(dir, cfg, n, plannerNoSigner{})
	if err != nil {
		t.Fatal(err)
	}
	if err = r.Enqueue(first); err != nil {
		t.Fatal(err)
	}
	if err = r.Step(context.Background()); err != nil || r.Status()[0].Phase != "complete" {
		t.Fatal("initial credit completion", err)
	}
	if err = r.Close(); err != nil {
		t.Fatal(err)
	}
	if err = n.Close(); err != nil {
		t.Fatal(err)
	}
	n, err = relay.OpenNetwork(networkCfg)
	if err != nil || n.Source.Current().Height != 100 || n.AuthenticatedStatus().DEXSequence != 0 {
		t.Fatal("cold source or DEX discovery state", err)
	}
	defer n.Close()
	r, err = relay.Open(dir, cfg, n, plannerNoSigner{})
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	if err = r.Step(context.Background()); err != nil || r.Status()[0].Phase != "complete" {
		t.Fatal("cold completed job was not freshly authenticated", err)
	}
	for _, job := range []relay.Job{empty, later} {
		if err = r.Enqueue(job); err != nil {
			t.Fatal(err)
		}
		if err = r.Step(context.Background()); err != nil {
			t.Fatal(err)
		}
	}
	for _, record := range r.Status() {
		if record.Phase != "complete" {
			t.Fatal("repeated empty/nonempty job did not reconcile", record.Phase, record.LastError)
		}
	}
	if n.AuthenticatedStatus().DEXSequence != 3 {
		t.Fatal("cold DEX proof chain not rediscovered")
	}
}
